/**
 * Generates tiny base64 blur placeholders for every image in public/images.
 * Run: node scripts/generate-blur.mjs
 * Output: src/config/image-blur.ts (consumed by ParallaxImage / Hero).
 */
import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const IMAGES_DIR = path.join(process.cwd(), 'public', 'images');
const OUT_FILE = path.join(process.cwd(), 'src', 'config', 'image-blur.ts');

const files = (await readdir(IMAGES_DIR)).filter((f) => /\.(jpe?g|png|webp|avif)$/i.test(f));

const entries = [];
for (const file of files) {
  const buffer = await sharp(path.join(IMAGES_DIR, file))
    .resize(12, 12, { fit: 'inside' })
    .jpeg({ quality: 45 })
    .toBuffer();
  entries.push([`/images/${file}`, `data:image/jpeg;base64,${buffer.toString('base64')}`]);
  console.log(`blur  ${file}  ${buffer.length}B`);
}

const body = `/**
 * AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.
 * Tiny base64 previews so images blur-up instead of popping in from an empty
 * frame while lazy-loading.
 */
export const imageBlur: Record<string, string> = {
${entries.map(([k, v]) => `  '${k}': '${v}',`).join('\n')}
};

export function getBlur(src: string): string | undefined {
  return imageBlur[src];
}
`;

await writeFile(OUT_FILE, body, 'utf8');
console.log(`\nWrote ${entries.length} placeholders → src/config/image-blur.ts`);
